export type MacroTemplate = {
  questionType: string;
  question: string;
  answer: string;
};

// 카테고리별 고정 매크로 템플릿
export const CATEGORY_MACROS: Record<string, MacroTemplate[]> = {
  '스니커즈/신발': [
    { questionType: 'SIZE',        question: '사이즈',    answer: '' },
    { questionType: 'WORN_COUNT',  question: '실착횟수',  answer: '' },
    { questionType: 'BOX',         question: '박스유무',  answer: '' },
    { questionType: 'DEFECT',      question: '하자여부',  answer: '' },
    { questionType: 'SOLE_WEAR',   question: '밑창마모',  answer: '' },
    { questionType: 'AUTH',        question: '정품인증',  answer: '' },
    { questionType: 'EXTRA_LACE',  question: '추가끈',    answer: '' },
    { questionType: 'STAIN',       question: '오염여부',  answer: '' },
    { questionType: 'RECEIPT',     question: '영수증',    answer: '' },
    { questionType: 'YEAR',        question: '연식',      answer: '' },
  ],
  '의류': [
    { questionType: 'SIZE',        question: '사이즈',    answer: '' },
    { questionType: 'MEASURE',     question: '실측기장',  answer: '' },
    { questionType: 'STAIN',       question: '오염여부',  answer: '' },
    { questionType: 'WASH',        question: '세탁여부',  answer: '' },
    { questionType: 'REPAIR',      question: '수선여부',  answer: '' },
    { questionType: 'TAG',         question: '택유무',    answer: '' },
    { questionType: 'MATERIAL',    question: '소재',      answer: '' },
    { questionType: 'FIT_PHOTO',   question: '착샷',      answer: '' },
    { questionType: 'AUTH',        question: '정품인증',  answer: '' },
    { questionType: 'PILLING',     question: '보풀상태',  answer: '' },
  ],
  '시계': [
    { questionType: 'MODEL',       question: '모델명',    answer: '' },
    { questionType: 'WARRANTY',    question: '보증서',    answer: '' },
    { questionType: 'FULL_SET',    question: '풀코여부',  answer: '' },
    { questionType: 'OVERHAUL',    question: '오버홀',    answer: '' },
    { questionType: 'YEAR',        question: '연식',      answer: '' },
    { questionType: 'SCRATCH',     question: '기스여부',  answer: '' },
    { questionType: 'DENT',        question: '찍힘여부',  answer: '' },
    { questionType: 'PARTS',       question: '구성품',    answer: '' },
    { questionType: 'OPERATION',   question: '작동상태',  answer: '' },
    { questionType: 'AUTH',        question: '정품인증',  answer: '' },
  ],
  '가방/패션잡화': [
    { questionType: 'SIZE',        question: '사이즈',    answer: '' },
    { questionType: 'WARRANTY',    question: '보증서',    answer: '' },
    { questionType: 'DUSTBAG',     question: '더스트백',  answer: '' },
    { questionType: 'CORNER_WEAR', question: '모서리마모', answer: '' },
    { questionType: 'INNER_STAIN', question: '내부오염',  answer: '' },
    { questionType: 'STRAP',       question: '스트랩유무', answer: '' },
    { questionType: 'HW_SCRATCH',  question: '금장기스',  answer: '' },
    { questionType: 'SHAPE',       question: '모양무너짐', answer: '' },
    { questionType: 'AUTH',        question: '정품인증',  answer: '' },
    { questionType: 'YEAR',        question: '연식',      answer: '' },
  ],
  '주얼리': [
    { questionType: 'MATERIAL',    question: '소재',      answer: '' },
    { questionType: 'WEIGHT',      question: '중량',      answer: '' },
    { questionType: 'SIZE',        question: '사이즈',    answer: '' },
    { questionType: 'WARRANTY',    question: '보증서',    answer: '' },
    { questionType: 'PARTS',       question: '구성품',    answer: '' },
    { questionType: 'DISCOLOR',    question: '변색여부',  answer: '' },
    { questionType: 'SCRATCH',     question: '잔기스',    answer: '' },
    { questionType: 'ENGRAVING',   question: '각인여부',  answer: '' },
    { questionType: 'STONE_LOSS',  question: '알빠짐여부', answer: '' },
    { questionType: 'AUTH',        question: '정품인증',  answer: '' },
  ],
  '트레이딩 카드': [
    { questionType: 'GRADE',       question: '등급',      answer: '' },
    { questionType: 'CONDITION',   question: '상태',      answer: '' },
    { questionType: 'CENTERING',   question: '센터링',    answer: '' },
    { questionType: 'LANGUAGE',    question: '언어',      answer: '' },
    { questionType: 'SCRATCH',     question: '기스여부',  answer: '' },
    { questionType: 'WHITENING',   question: '백화현상',  answer: '' },
    { questionType: 'CORNER',      question: '모서리까짐', answer: '' },
    { questionType: 'EDITION',     question: '에디션',    answer: '' },
    { questionType: 'SLEEVE',      question: '슬리브포장', answer: '' },
    { questionType: 'AUTH',        question: '정품인증',  answer: '' },
  ],
  '피규어/아트토이/굿즈': [
    { questionType: 'OPENED',      question: '개봉여부',  answer: '' },
    { questionType: 'BOX',         question: '박스상태',  answer: '' },
    { questionType: 'PARTS',       question: '파츠누락',  answer: '' },
    { questionType: 'PAINT',       question: '도색미스',  answer: '' },
    { questionType: 'JOINT',       question: '관절상태',  answer: '' },
    { questionType: 'DISPLAY',     question: '전시여부',  answer: '' },
    { questionType: 'DUST',        question: '먼지오염',  answer: '' },
    { questionType: 'DISCOLOR',    question: '변색여부',  answer: '' },
    { questionType: 'MANUAL',      question: '설명서',    answer: '' },
    { questionType: 'AUTH',        question: '정품인증',  answer: '' },
  ],
  '전자기기': [
    { questionType: 'MODEL',       question: '모델명',    answer: '' },
    { questionType: 'BATTERY',     question: '배터리효율', answer: '' },
    { questionType: 'STORAGE',     question: '용량',      answer: '' },
    { questionType: 'REPAIR',      question: '수리이력',  answer: '' },
    { questionType: 'WARRANTY',    question: '보증기간',  answer: '' },
    { questionType: 'DENT',        question: '외관찍힘',  answer: '' },
    { questionType: 'SCREEN',      question: '액리기스',  answer: '' },
    { questionType: 'PARTS',       question: '구성품',    answer: '' },
    { questionType: 'OPERATION',   question: '정상작동',  answer: '' },
    { questionType: 'RESET',       question: '초기화여부', answer: '' },
  ],
  '미술품/판화': [
    { questionType: 'ARTIST',      question: '작가명',    answer: '' },
    { questionType: 'COA',         question: '보증서',    answer: '' },
    { questionType: 'EDITION_NO',  question: '에디션번호', answer: '' },
    { questionType: 'SIZE',        question: '사이즈',    answer: '' },
    { questionType: 'FRAME',       question: '액자여부',  answer: '' },
    { questionType: 'YEAR',        question: '제작연도',  answer: '' },
    { questionType: 'STORAGE',     question: '보관상태',  answer: '' },
    { questionType: 'DISCOLOR',    question: '변색여부',  answer: '' },
    { questionType: 'TECHNIQUE',   question: '작품기법',  answer: '' },
    { questionType: 'SIGNATURE',   question: '서명여부',  answer: '' },
  ],
  '골동품/앤틱': [
    { questionType: 'ERA',         question: '연대',      answer: '' },
    { questionType: 'ORIGIN',      question: '출처',      answer: '' },
    { questionType: 'MATERIAL',    question: '재질',      answer: '' },
    { questionType: 'RESTORATION', question: '수리복원',  answer: '' },
    { questionType: 'DAMAGE',      question: '파손여부',  answer: '' },
    { questionType: 'DIMENSIONS',  question: '크기무게',  answer: '' },
    { questionType: 'APPRAISAL',   question: '감정서',    answer: '' },
    { questionType: 'WEAR',        question: '사용감',    answer: '' },
    { questionType: 'AUTHENTIC',   question: '진품여부',  answer: '' },
    { questionType: 'PRESERVATION',question: '보존상태',  answer: '' },
  ],
  '기타': [
    { questionType: 'DESCRIPTION', question: '상세설명',  answer: '' },
    { questionType: 'CONDITION',   question: '상태',      answer: '' },
    { questionType: 'USAGE',       question: '사용기간',  answer: '' },
    { questionType: 'DEFECT',      question: '하자여부',  answer: '' },
    { questionType: 'PARTS',       question: '구성품',    answer: '' },
    { questionType: 'PURCHASE',    question: '구매처',    answer: '' },
    { questionType: 'EXPIRY',      question: '유통기한',  answer: '' },
    { questionType: 'OPERATION',   question: '작동여부',  answer: '' },
    { questionType: 'DIMENSIONS',  question: '크기무게', answer: '' },
    { questionType: 'RECEIPT',     question: '영수증',    answer: '' },
  ],
};
