export const styles: { [key: string]: React.CSSProperties } = {
  page: {
    width: '100%',
    boxSizing: 'border-box',
    maxWidth: 1200, 
    margin: '0 auto',
    padding: '40px 20px',
    display: 'flex',
    flexDirection: 'column',
    gap: 32,
  },
  center: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 400,
  },
  spinner: {
    width: 40, height: 40,
    border: '3px solid #333',
    borderTopColor: '#d9b36d',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  sectionBox: {
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid #2e2e40',
    borderRadius: 16,
    padding: '44px 56px',
    backgroundColor: '#0c0c14',
  },
  // ── 상단 프로필 영역 ──
  profileRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 40,
  },
  avatarWrapper: {},
  avatar: {
    width: 140,
    height: 140,
    borderRadius: '50%',
    objectFit: 'cover',
  },
  avatarFallback: {
    width: 140,
    height: 140,
    borderRadius: '50%',
    backgroundColor: '#1e1e2d',
    color: '#d9b36d',
    fontSize: 48,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  profileInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  nameRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
  },
  nickname: {
    margin: 0,
    fontSize: 26,
    fontWeight: 700,
    color: '#fff',
  },
  followBtn: {
    padding: '8px 22px',
    borderRadius: 24,
    backgroundColor: '#fff',
    color: '#111827',
    fontSize: 14,
    fontWeight: 700,
    border: 'none',
    cursor: 'pointer',
  },
  textBtn: {
    border: 'none',
    background: 'none',
    color: '#888',
    fontSize: 14,
    cursor: 'pointer',
  },
  intro: {
    margin: 0,
    fontSize: 15,
    color: '#ddd',
    lineHeight: 1.5,
  },
  snsRow: {
    display: 'flex',
    gap: 20,
    marginTop: 4,
  },
  snsLink: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    color: '#fff',
    textDecoration: 'none',
    fontSize: 16,
    fontWeight: 600,
  },
  // ── 통계 박스 ──
  statsBox: {
    marginTop: 12,
    border: '1px solid #2e2e40',
    borderRadius: 12,
    padding: '24px 0',
    display: 'flex',
    alignItems: 'center',
    width: '420px', 
  },
  statItem: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 6,
  },
  statValue: {
    fontSize: 22,
    fontWeight: 700,
    color: '#fff',
  },
  statLabel: {
    fontSize: 13,
    color: '#888',
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#2e2e40',
  },
  // ── 하단 탭 영역 ──
  tabsHeader: {
    display: 'flex',
    gap: 24,
    borderBottom: '1px solid #2e2e40',
    marginBottom: 32,
  },
  tabBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    background: 'none',
    border: 'none',
    borderBottomWidth: 2,
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    padding: '0 8px 16px 8px',
    fontSize: 16,
    fontWeight: 700,
    color: '#888',
    cursor: 'pointer',
    marginBottom: -1, /* 겹쳐서 자연스럽게 */
    transition: '0.2s',
  },
  tabActive: {
    color: '#d9b36d',
    borderBottomColor: '#d9b36d',
  },
  listContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  empty: {
    textAlign: 'center',
    color: '#888',
    padding: '60px 0',
    fontSize: 15,
  },
  // ── 공지사항 UI ──
  createNoticeBtn: {
    padding: '8px 16px',
    backgroundColor: '#d9b36d',
    color: '#111',
    border: 'none',
    borderRadius: 8,
    fontWeight: 700,
    fontSize: 14,
    cursor: 'pointer',
  },
  noticeCard: {
    border: '1px solid #2e2e40',
    borderRadius: 12,
    padding: '28px 32px',
    backgroundColor: '#0f0f16',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  noticeIconRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  noticeTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 700,
    color: '#fff',
  },
  noticeContent: {
    margin: '4px 0 0 30px',
    fontSize: 14,
    color: '#aaa',
    lineHeight: 1.6,
  },
  noticeMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    marginLeft: 30,
  },
  dateText: {
    fontSize: 13,
    color: '#666',
  },
  actionBtn: {
    background: 'none',
    border: 'none',
    color: '#888',
    fontSize: 13,
    cursor: 'pointer',
    textDecoration: 'underline',
  },
  // ── 일반 상품 카드 예시용 (낙찰 이력) ──
  saleRow: {
    display: 'flex',
    padding: '16px 0',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  saleIconCircle: {
    width: 64,
    height: 64,
    borderRadius: '50%',
    backgroundColor: '#1c1c28',
    border: '1.5px solid #d9b36d',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saleInfoBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  badgeGreen: {
    alignSelf: 'flex-start',
    backgroundColor: '#1b4a3c',
    color: '#4ade80',
    padding: '4px 8px',
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 20,
  },
  badgeBlue: {
    alignSelf: 'flex-start',
    backgroundColor: '#183b5f',
    color: '#60a5fa',
    padding: '4px 8px',
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 20,
  },
  saleTitleLine: {
    margin: '2px 0 0 0',
    fontSize: 16,
    fontWeight: 700,
    color: '#fff',
  },
  saleDateLine: {
    margin: 0,
    fontSize: 13,
    color: '#888',
  },
  salePriceText: {
    fontSize: 16,
    fontWeight: 700,
    color: '#fff',
  },
  saleStatusText: {
    fontSize: 13,
    color: '#888',
  },
  // ── 공지사항 수정/등록 모달 ──
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.7)',
    zIndex: 999,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalContent: {
    backgroundColor: '#1a1a28',
    border: '1px solid #2e2e40',
    borderRadius: 16,
    width: 500,
    padding: 32,
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    boxShadow: '0 8px 30px rgba(0,0,0,0.5)',
  },
  modalTitle: {
    margin: 0,
    color: '#fff',
    fontSize: 20,
    fontWeight: 700,
  },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    backgroundColor: '#0f0f16',
    color: '#fff',
    border: '1px solid #2e2e40',
    borderRadius: 8,
    padding: 14,
    fontSize: 15,
  },
  textarea: {
    width: '100%',
    boxSizing: 'border-box',
    backgroundColor: '#0f0f16',
    color: '#fff',
    border: '1px solid #2e2e40',
    borderRadius: 8,
    padding: 14,
    fontSize: 15,
    minHeight: 140,
    resize: 'none',
  },
  modalBtnRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 10,
  },
  btnCancel: {
    padding: '10px 24px',
    backgroundColor: '#333',
    color: '#ddd',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 600,
  },
  btnSubmit: {
    padding: '10px 24px',
    backgroundColor: '#d9b36d',
    color: '#111',
    fontWeight: 700,
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
  },
  // ── 낙찰 이력 (Escrow) 상세 모달 전용 ──
  escrowDetailModal: {
    backgroundColor: '#0c0c14',
    border: '1px solid #2e2e40',
    borderRadius: 16,
    width: 480,
    padding: '36px 40px',
    display: 'flex',
    flexDirection: 'column',
    gap: 32,
    boxShadow: '0 8px 30px rgba(0,0,0,0.5)',
  },
  escrowDetailTitle: {
    margin: 0,
    color: '#fff',
    fontSize: 22,
    fontWeight: 700,
  },
  escrowProductBlock: {
    display: 'flex',
    gap: 24,
    alignItems: 'stretch',
  },
  escrowProductImage: {
    width: 140,
    height: 140,
    borderRadius: 12,
    objectFit: 'cover',
    backgroundColor: '#fff',
  },
  escrowProductInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 16,
  },
  escrowRowInfo: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  escrowLabel: {
    fontSize: 15,
    color: '#ccc',
    fontWeight: 500,
  },
  escrowValue: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 700,
  },
  escrowValueGold: {
    fontSize: 16,
    color: '#d9b36d',
    fontWeight: 700,
  },
  escrowDateStr: {
    marginTop: 'auto',
    alignSelf: 'flex-start',
    fontSize: 14,
    color: '#888',
  },
  escrowSectionTitleBlock: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  escrowSectionTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 18,
    fontWeight: 700,
    color: '#fff',
    margin: 0,
  },
  escrowTrackingText: {
    fontSize: 14,
    color: '#d9b36d',
    textDecoration: 'underline',
  },
  escrowInnerBox: {
    border: '1px solid #2e2e40',
    borderRadius: 12,
    padding: '20px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  escrowInnerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 15,
  },
  escrowInnerLeft: {
    color: '#ccc',
  },
  escrowInnerRight: {
    color: '#fff',
  },
  escrowInnerText: {
    margin: 0,
    fontSize: 15,
    color: '#ccc',
    lineHeight: 1.6,
  },
  escrowCloseBtnBlock: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: 8,
  },
  escrowCloseBtn: {
    padding: '12px 48px',
    backgroundColor: '#f5f5f5',
    color: '#111',
    border: 'none',
    borderRadius: 24,
    fontSize: 16,
    fontWeight: 700,
    cursor: 'pointer',
  },
};
