spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gcp:
      storage:
        credentials:
          location: file:${GCS_CREDENTIALS_PATH}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

logging:
  level:
    com.ssafy.be: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

server:
  tomcat:
    mbean-enabled: true
  threads:
    max: 500       # 기본값 200 -> 500으로 증가
    min-spare: 50  # 유지할 최소 스레드
    max-connections: 1000 # 톰캣이 유지할 수 있는 최대 커넥션 수

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: hanok-backend
      namespace: production
    lettuce:
      enabled: true