spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gcp:
      storage:
        credentials:
          location: file:${GCS_CREDENTIALS_PATH}

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.ssafy.be: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
