spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update

  autoconfigure:
    exclude:
      - com.google.cloud.spring.autoconfigure.secretmanager.GcpSecretManagerAutoConfiguration

logging:
  level:
    com.ssafy.be: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

server:
  port: 8081