spring:
  application:
    name: be

  cloud:
    gcp:
      storage:
        bucket: ${GCS_BUCKET_NAME:hanok-storage}
        credentials:
          location: ${GCS_CREDENTIALS_PATH:classpath:gcs-key.json}
      secretmanager:
        enabled: false


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:}:${DB_PORT:}/${DB_NAME:}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 50  # 기본값 10 -> 50으로 증가
      minimum-idle: 10
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

      web:
        pageable:
          serialization-mode: via-dto
  #      password: ${REDIS_PASSWORD:}
  #      ssl:
  #        enabled: ${REDIS_SSL_ENABLED:false}
  jpa:
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:}

was:
  cors-allow-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:5174}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.ssafy.be
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

portone:
  base-url: ${PORTONE_BASE_URL:}
  store-id: ${PORTONE_STORE_ID:}
  secret:
      key: ${PORTONE_SECRET_KEY:}
      webhook: ${PORTONE_SECRET_WEBHOOK:} # 추후 운영 서버 도메인으로 웹훅 재등록 필요

livekit:
  url: ws://hanok-livekit:7880
  api-key: ${LIVEKIT_API_KEY:devkey}
  api-secret: ${LIVEKIT_API_SECRET:devsecretkeythatisatleast32characters}

bizno:
  api:
    key: ${BIZNO_API_KEY}

blockchain:
  rpc-url: ${BLOCKCHAIN_RPC_URL:http://127.0.0.1:8545}
  private-key: ${SERVER_WALLET_PRIVATE_KEY:0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
  contract-address: ${CONTRACT_ADDRESS:0x5FbDB2315678afecb367f032d93F642f64180aa3}