export const STEPS = [
  { id: 1, label: '개인/법인' },
  { id: 2, label: '판매자 약관 동의' },
  { id: 3, label: '정산 계좌' },
  { id: 4, label: '판매자 정보 등록' },
];

export const TERMS_CONTENT = [
  {
    title: '판매 상품 등록',
    body: '판매자는 실제 보유한 상품만 등록할 수 있으며 상품의 상태, 구성품, 하자 여부 등 중요한 정보를 정확하게 기재해야 합니다. 허위 정보, 과장된 설명 또는 타인의 지식재산권을 침해하는 상품 등록은 금지됩니다. 잘못된 정보로 인해 발생하는 분쟁에 대한 책임은 판매자에게 있습니다.',
  },
  {
    title: '경매 진행',
    body: '판매자는 경매 시작 가격, 입찰 단위 및 경매 시간을 명확하게 설정해야 하며 경매 진행 중 고의적으로 상품 정보를 변경하거나 입찰을 조작하는 행위를 해서는 안 됩니다. 낙찰자가 결정된 이후 판매자는 정당한 사유 없이 거래를 취소할 수 없습니다.',
  },
  {
    title: '배송 및 거래',
    body: '낙찰이 완료된 경우 판매자는 정해진 기간 내에 상품을 발송해야 하며 안전하게 포장하여 배송해야 합니다. 배송 정보는 플랫폼에 정확하게 등록해야 하며 배송 지연, 미배송 또는 고의적인 거래 지연이 발생할 경우 플랫폼 정책에 따라 제재될 수 있습니다.',
  },
];

export const BANKS = [
  // 은행
  { code: '003', name: '기업은행' },
  { code: '004', name: '국민은행' },
  { code: '007', name: '수협은행' },
  { code: '011', name: '농협은행' },
  { code: '012', name: '지역농·축협' },
  { code: '002', name: '산업은행' },
  { code: '020', name: '우리은행' },
  { code: '023', name: 'SC은행' },
  { code: '027', name: '한국씨티은행' },
  { code: '031', name: '대구은행' },
  { code: '032', name: '부산은행' },
  { code: '034', name: '광주은행' },
  { code: '035', name: '제주은행' },
  { code: '037', name: '전북은행' },
  { code: '039', name: '경남은행' },
  { code: '045', name: '새마을금고' },
  { code: '048', name: '신협' },
  { code: '050', name: '저축은행' },
  { code: '054', name: 'HSBC' },
  { code: '055', name: '도이치' },
  { code: '057', name: 'JP모간' },
  { code: '060', name: 'BOA' },
  { code: '061', name: 'BNP파리바' },
  { code: '062', name: '중국공상' },
  { code: '063', name: '중국' },
  { code: '064', name: '산림조합' },
  { code: '067', name: '중국건설' },
  { code: '071', name: '우체국' },
  { code: '081', name: '하나은행' },
  { code: '088', name: '신한은행' },
  { code: '089', name: '케이뱅크' },
  { code: '090', name: '카카오뱅크' },
  { code: '092', name: '토스뱅크' },
  // 증권사
  { code: '209', name: '유안타증권' },
  { code: '218', name: 'KB증권' },
  { code: '221', name: '상상인증권' },
  { code: '224', name: 'BNK투자증권' },
  { code: '225', name: 'IBK투자증권' },
  { code: '227', name: '다올투자증권' },
  { code: '238', name: '미래에셋증권' },
  { code: '240', name: '삼성증권' },
  { code: '243', name: '한국투자증권' },
  { code: '247', name: 'NH투자증권' },
  { code: '261', name: '교보증권' },
  { code: '262', name: '하이투자증권' },
  { code: '263', name: '현대차증권' },
  { code: '264', name: '키움증권' },
  { code: '265', name: '이베스트투자증권' },
  { code: '266', name: '에스케이증권' },
  { code: '267', name: '대신증권' },
  { code: '269', name: '한화투자증권' },
  { code: '270', name: '하나증권' },
  { code: '271', name: '토스증권' },
  { code: '278', name: '신한투자증권' },
  { code: '279', name: 'DB금융투자' },
  { code: '280', name: '유진투자증권' },
  { code: '287', name: '메리츠증권' },
  { code: '288', name: '카카오페이증권' },
  { code: '290', name: '부국증권' },
  { code: '291', name: '신영증권' },
  { code: '292', name: '케이프투자증권' },
  { code: '294', name: '한국포스증권' },
];

export const COURIERS = [
  { code: '04', name: 'CJ대한통운' },
  { code: '01', name: '우체국택배' },
  { code: '05', name: '한진택배' },
  { code: '08', name: '롯데택배' },
  { code: '06', name: '로젠택배' },
  { code: '22', name: '대신택배' },
  { code: '23', name: '경동택배' },
  { code: '32', name: '합동택배' },
  { code: '46', name: 'CU 편의점택배' },
  { code: '24', name: 'GS Postbox 택배' },
];
